### ISSUE TITLE
SOLOAuth

### ISSUE THREAD

**Issue by nnnlog** [solo5star/Plugins_PocketMine#5]
SOLOAuth에 UUID (Cid)가 일치할 때 ip 등에 관계없이 로그인 되는 기능 (될 수 있다면) 추가해봐도 되나요..?

**Comment by solo5star** [comment]
네 얼마든지요  근데 코드가 완전 스파게티라...

**Comment by nnnlog** [comment]
@solo5star 허락해주셔서 감사합니다.
